### PR TITLE
Adding Guzzle 7 Support

### PR DESCRIPTION
**Pull request by iulyanp**

### CODE REVIEW

**Review by mihaileu — APPROVED** [review]

**Comment by mihaileu** [comment]
@dshafik we need this change.

**Comment by iulyanp** [comment]
@dshafik It seems that it solves also this issue [#38](https://github.com/akamai/AkamaiOPEN-edgegrid-php-client/issues/38)

**Comment by dshafik** [comment]
@iulyanp I'm no longer with Akamai, sorry

**Comment by mihaileu** [comment]
who is maintaining this repo ? 
@dctheobald @akamaimike could you please help us ?

**Comment by ghost** [comment]
Our Developer Experience team will maintain the EdgeGrid libraries and plugins moving forward. If you are employed at Akamai, please get in touch with me directly.

**Comment by iulyanp** [comment]
Hi @akamaimike

We are not working at Akamai but we use this library on our production code as we are a big Akamai client and we would like to upgrade our projects to Guzzle 7.

Could you please help us with this PR?

From what I see the library is unmaintained from 1 Sep 2017. Should we stop using it?

Best regards,

**Comment by mihaileu** [comment]
@akamaimike should we stop using this library ? (there's no activity here in the last 4 years)

**Comment by ghost** [comment]
> @akamaimike should we stop using this library ? (there's no activity here in the last 4 years)

Hi mihaileu, our Engineering teams are in the process of updating the EdgeGrid libraries to the latest versions including the PHP library. There is no ETA on this yet though.

**Comment by jskorlol** [comment]
when update ?

**Comment by mihaileu** [comment]
@securitylevelup any news ?

**Comment by jspear623** [comment]
@securitylevelup - It would be really good to get an update on this. People need to upgrade their projects and we're all waiting on this. Thanks.

**Comment by ghost** [comment]
Thanks for the reminder. I have spoken to our Developer Experience Engineering teams and an upgrade for this EdgeGrid library is in the works right now, this will support PHP 8 and Guzzle. I will ask the Engineering team to add a more meaningful update in this thread as I am not directly involved with the coding/testing on this.

**Comment by dmitryuk** [comment]
@securitylevelup no news?

**Comment by ghost** [comment]
The development work is ongoing on this upgrade, there should be a release coming soon.

**Comment by dmitryuk** [comment]
Thanks, also "monolog/monolog" should be updated

**Comment by chrispenny** [comment]
@securitylevelup I (we) appreciate the comms, but could your development team please provide a delivery date so that we can make informed decisions about whether we continue to use this library or not?

Many other libraries have moved to Guzzle 7 as part of their PHP 8 upgrades. PHP 7 is EOL in November, so a lot of us are working towards that date.

I have multiple projects (for Enterprise level clients of Akamai) that are currently blocked by this library not supporting Guzzle 7. I either need to tell them that this is on its way in time for us to upgrade before PHP 7 EOL, or I need to tell them that we're going to have to roll our own.

Thanks

**Comment by dmitryuk** [comment]
Akamai team, still no news?

**Comment by lkowalsk-akamai-com** [comment]
Hi, new version of this package was released today - https://github.com/akamai/AkamaiOPEN-edgegrid-php-client/releases/tag/2.0.0 
Please take a look as it makes the package up to date

**Pull request closed without merging**
